"use client";

import { useCallback, useEffect, useState } from "react";

// Live, shareable version of the PayLoop pitch deck. Mirrors the .pptx
// generated by scripts/build-pitch.py. Navigate with ←/→ or the buttons.

const slides = [
  {
    title: "PayLoop",
    sub: "Get paid in seconds, cash out at home.",
    bullets: [
      "Invoice + escrow for freelancers, built on Stellar Soroban",
      "USDC payments settle in ~5 seconds for fractions of a cent",
      "Every payment is an on-chain income record — portable and tamper-proof",
    ],
  },
  {
    title: "The problem",
    sub: "Global clients, broken payments.",
    bullets: [
      "PayPal/Payoneer: 2–5 day holds, 3–5% fees plus 5–8% FX markup",
      "African freelancers wait weeks to see money for work already done",
      "No verifiable income trail — lenders and clients can't check your history",
      "Freelancing is exploding, but the rails still punish the sellers",
    ],
  },
  {
    title: "The solution",
    sub: "PayLoop — a payment loop that works for the freelancer.",
    bullets: [
      "Create an invoice on-chain, share a /pay link, get paid in one wallet click",
      "Instant settlement: USDC moves client → freelancer atomically",
      "Portable, on-chain invoice history = your reputation and income proof",
      "Cash out to Naira through a licensed anchor (SEP-24 off-ramp)",
    ],
  },
  {
    title: "How it works",
    sub: "Create → share → client pays → cash out.",
    bullets: [
      "1. Freelancer creates an invoice (client, amount, description)",
      "2. Client opens the shared link and funds it in one click",
      "3. USDC lands with the freelancer instantly, recorded on-chain",
      "4. Freelancer withdraws to their local bank via an anchor",
    ],
  },
  {
    title: "Market opportunity",
    sub: "A large, growing, under-served market.",
    bullets: [
      "Nigerian freelance & gig economy is among the fastest-growing in Africa",
      "Stablecoin remittance / payout volumes growing rapidly in the region",
      "Fees today cost freelancers 8–13% of every cross-border payment",
      "PayLoop attacks speed, cost, and trust — the three blockers at once",
    ],
  },
  {
    title: "Architecture",
    sub: "Stellar Soroban + Next.js. No app database.",
    bullets: [
      "Smart contract (Rust/Soroban) is the source of truth for invoices",
      "Next.js web app, Freighter wallet, deployed on Vercel",
      "Public on-chain activity feed — verifiable usage proof",
      "Sentry monitoring + Vercel analytics + in-app feedback loop",
      "Anchor off-ramp path documented and mocked end-to-end (SEP-24)",
    ],
  },
  {
    title: "Traction",
    sub: "Live on Stellar testnet, iterating on real feedback.",
    bullets: [
      "50+ testnet users onboarded with real wallet transactions",
      "Invoices created and paid on-chain — public and verifiable",
      "User survey: strong average product rating, 0% negative intent",
      "Feedback-driven iteration: history, preview, PDF export, reminders, walkthrough, dark mode",
    ],
  },
  {
    title: "Growth strategy",
    sub: "From 50 testnet users to a live product.",
    bullets: [
      "Onboard freelancer communities in design, writing and dev circles",
      "Reduce friction: one-click onboarding, tutorial, testnet faucet",
      "Land a licensed anchor for the real USDC → Naira off-ramp",
      "Word-of-mouth loop: every client who pays becomes a freelancer user",
      "Feedback funnel (form + in-app widget) drives each iteration",
    ],
  },
  {
    title: "Roadmap",
    sub: "Next on the build.",
    bullets: [
      "Live USDC ↔ Naira anchor off-ramp (SEP-24)",
      "Milestone / held escrow for larger projects",
      "On-chain reputation score and income proof API",
      "Recurring / retainer invoices and multi-stablecoin",
      "Agency batch payouts and team accounts",
    ],
  },
  {
    title: "The ask",
    sub: "What we're building toward.",
    bullets: [
      "Hackathon / grant validation to fund the anchor integration",
      "Design partners: freelancers willing to pay in USDC today",
      "Advisors with anchor & compliance experience",
      "We ship a full, tested, deployed product — on testnet today",
    ],
  },
];

export default function PitchPage() {
  const [i, setI] = useState(0);

  const next = useCallback(() => setI((n) => Math.min(slides.length - 1, n + 1)), []);
  const prev = useCallback(() => setI((n) => Math.max(0, n - 1)), []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight" || e.key === " ") {
        e.preventDefault();
        next();
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        prev();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [next, prev]);

  const s = slides[i];

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">PayLoop — Pitch</h1>
          <p className="mt-1 text-sm text-slate-400">
            Slide {i + 1} of {slides.length} · use ←/→ keys
          </p>
        </div>
        <a
          href="https://github.com/Yormee-103/PayLoop/blob/main/docs/pitch/PayLoop-Pitch-Deck.pptx"
          target="_blank"
          rel="noopener noreferrer"
          className="btn-ghost text-xs"
        >
          ⬇ Download .pptx
        </a>
      </div>

      <div className="card min-h-[26rem] space-y-6 p-8 sm:p-12">
        <div>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            {s.title}
          </h2>
          <p className="mt-2 text-brand-300">{s.sub}</p>
        </div>
        <ul className="space-y-3">
          {s.bullets.map((b, idx) => (
            <li key={idx} className="flex gap-3 text-base text-slate-200 sm:text-lg">
              <span className="mt-0.5 text-brand-400">•</span>
              <span>{b}</span>
            </li>
          ))}
        </ul>
      </div>

      <div className="flex items-center justify-between">
        <button onClick={prev} disabled={i === 0} className="btn-ghost text-sm">
          ← Prev
        </button>
        <div className="flex gap-1.5">
          {slides.map((_, n) => (
            <button
              key={n}
              onClick={() => setI(n)}
              aria-label={`Go to slide ${n + 1}`}
              className={`h-2 rounded-full transition-all ${
                n === i ? "w-6 bg-brand-400" : "w-2 bg-white/20 hover:bg-white/40"
              }`}
            />
          ))}
        </div>
        <button
          onClick={next}
          disabled={i === slides.length - 1}
          className="btn-primary text-sm"
        >
          Next →
        </button>
      </div>
    </div>
  );
}
